#!/bin/bash

while [ ! -z "$1" ]; do
case $1 in
	"--push")
		PUSH=1
		shift
		;;
	"--project")
		PRJNAME=$2
		shift 2
		;;
	"-m")
		CSTMSG=1
		MSG=$2
		shift 2
		;;
	"--parent")
		PARENT=$2
		shift 2
		;;
esac
done


if [ "x${PRJNAME}" == "x" ]; then
	PRJNAME=$(cat .osc/_project)
fi
for pkg in $(osc ls ${PRJNAME}); do
	if [ -z "${PARENT}" ]; then
		TARGET=$(osc cat ${PRJNAME}/${pkg}/_link | grep -o 'project="\([^"]*\)' | sed 's:project="::')
	else
		TARGET=${PARENT}
	fi
	if [ "$(osc rdiff ${PRJNAME} ${pkg} ${TARGET} ${pkg} 2>/dev/null | wc -l)" -gt 0 -a ! $(osc rq list ${PRJNAME} ${pkg} --exclude-target-project=${PRJNAME} 2>/dev/null | grep -c -v "No results for") -gt 0 ]; then
		if [ "0$PUSH" -eq 1 ]; then
			if [ ! -z "$TARGET" ]; then
				echo -e "Pushing package $PRJNAME/$pkg "
				osc sr ${PRJNAME} ${pkg} ${TARGET} -m "${MSG}"
				unset TARGET
			else
				echo "Could not guess parent project for ${PRJNAME}/${pkg}; likely not a link"
			fi
		else
			echo -n Package $PRJNAME $pkg needs to be submitted
			if [ ! -z "${PARENT}" ]; then echo -n " to parent project ${PARENT}"; fi
			echo -e
		fi
	fi;
done
