#!/usr/bin/env python3
# Compatibility wrapper delegating to geckopit-cli --upgrade
import os, sys

script_dir = os.path.dirname(os.path.realpath(__file__))
cli_path = os.path.join(script_dir, 'geckopit-cli')
args = [cli_path, '--upgrade'] + sys.argv[1:]
os.execv(cli_path, args)
